<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "debug": {
                        "component": "Training_Js/js/layout-debug",
                        "config" : {
                            "xml": "<?= $escaper->escapeJs($block->getLayout()->getXmlString()) ?>"
                        }
                    }
                }
            }
        }
    }
</script>
